import Loading from "@/assets/icons/Loading";
import Button from "@/components/Atoms/Button";
import Input from "@/components/Atoms/Input";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [ name, setName ] = useState<string>()

  return (
    <>
      <Head>
        <title>Gerenciador de Pedidos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
      >
        <main>
          <Input
            id="input-name"
            value={name}
            onChange={setName}
            trim
            icon={<Loading/>}
          />
          <Button 
            text="Confirmar" 
            type="default"
            onClick={() => console.log('opaa')}
          />
        </main>
        <footer>
        </footer>
      </div>
    </>
  );
}