import Loading from "@/assets/icons/Loading";
import Button from "@/components/Atoms/Button";
import Input from "@/components/Atoms/Input";
import Select from "@/components/Atoms/Select";
import Modal from "@/components/Molecules/Modal";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [openModal, setOpenModal] = useState(false)

  return (
    <>
      <Head>
        <title>Gerenciador de Pedidos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
      >
        <main>
          <Button text="Abrir modal" onClick={() => setOpenModal(true)}/>
          <Modal
            opened={openModal}
            close={() => setOpenModal(false)}
            title="Cadastrar Chamado" 
            width="50%" 
          >
            <div>adsas</div>
          </Modal>
        </main>
        <footer>
        </footer>
      </div>
    </>
  );
}